config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :users, only: :show

  root 'questions#index'

  concern :votable do
    member do
      patch 'like'
      patch 'dislike'
      delete 'unvote'
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end

  get 'search' => 'search#search'
  post 'search' => 'search#search'

  resources :questions, concerns: [:votable, :commentable], shallow: true do
    resources :subscriptions, only: [:create, :destroy]
    resources :answers, concerns: [:votable, :commentable] do
      member do
        patch 'set_best'
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers
      end
    end
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  include Votable
  include Attachable
  include Commentable

  belongs_to :user
  has_many :answers, dependent: :destroy

  has_many :subscriptions, dependent: :destroy
  has_many :users, through: :subscriptions, dependent: :destroy

  validates :user_id, :title, :body, presence: true

  scope :digest, -> { where("created_at >= ?", 1.day.ago) }

  after_create :subscribe

  private
    def subscribe
      user.subscribe(self)
    end
end

app/controllers/api/v1/questions_controller.rb
class Api::V1::QuestionsController < Api::V1::BaseController
  before_action :find_question, only: :show

  def index
    authorize :api
    respond_with Question.all, each_serializer: Api::V1::QuestionCollectionSerializer
  end

  def show
    authorize :api
    respond_with @question, serializer: Api::V1::QuestionSerializer
  end

  def create
    authorize :api
    respond_with(@question = current_resource_owner.questions.create(question_params))
  end

  private
    def find_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:title, :body)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  include Voted

  before_action :authenticate_user!, except: [:index, :show]
  before_action :load_question, only: [:show, :update, :destroy, :subscribe, :unsubscribe]
  after_action :publish_to, only: [:create, :update, :destroy]

  respond_to :js, only: [:update]
  respond_to :json, only: [:subscribe, :unsubscribe]

  def index
    authorize Question
    respond_with(@questions = Question.all)
  end

  def show
    authorize @question
    respond_with(@question)
  end

  def new
    authorize Question
    respond_with(@question = Question.new)
  end

  def create
    authorize Question
    respond_with(@question = current_user.questions.create(question_params))
  end

  def update
    authorize @question
    @question.update(question_params)
    respond_with(@question)
  end

  def destroy
    authorize @question
    respond_with(@question.destroy)
  end

  def subscribe
    authorize @question
    current_user.subscribe(@question)
    render json: @question.to_json
  end

  def unsubscribe
    authorize @question
    current_user.unsubscribe(@question)
    render json: @question.to_json
  end

  private
    def load_question
      @question = Question.find(params[:id])
    end

    def publish_to
      PrivatePub.publish_to(
        "/questions", question: @question.to_json, action: self.action_name
      ) if @question.errors.empty?
    end

    def question_params
      params.require(:question).permit(
        :title, :body, attachments_attributes: [:id, :file, :_destroy]
      )
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.slim
= form_for @question, remote: true, html: { class: "form-horizontal edit_question" } do |f|
  .row
    .col-xs-1.col-xs-offset-11
      = link_to '#', class: "link-close" do
        span.glyphicon.glyphicon-remove
  .row
    .col-xs-12
      .form-group
        .col-sm-2
          = f.label :title, class: "control-label"
        .col-sm-10
          = f.text_field :title, class: "form-control"
      .form-group
        .col-sm-2
          = f.label :body, class: "control-label"
        .col-sm-10
          = f.text_area :body, class: "form-control"
      .attachments_form
        = f.fields_for :attachments do |attachment|
          = render 'layouts/attachment_fields', f: attachment, object: @question
      .form-group
        .col-sm-offset-2.col-sm-10.add_attachment
          = link_to_add_association 'Add file', f, :attachments,
            partial: 'layouts/attachment_fields', class: "btn btn-default"
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.submit "Save", class: "btn btn-default"

app/views/questions/_question.html.slim
.col-xs-2.votes
  = render 'layouts/vote_links', object: @question
.col-xs-9.col-xs-offset-1
  .row
    h3 = @question.title
    p = @question.body
  .row.attachments-list
    = render 'layouts/attachments', object: @question
  .row.actions
    .row
      ul.nav.nav-pills
        - if policy(@question).update?
          li => link_to 'Edit', '#', class: 'edit_question'
        - if policy(@question).destroy?
          li => link_to 'Delete', @question, method: :delete
        - if policy(@question).subscribe?
          li.subscription => link_to 'Subscribe', question_subscriptions_path(@question),
            method: :post, remote: true, data: { type: :json },
            class: 'link-subscribe'
        - if policy(@question).unsubscribe?
          li.unsubscription => link_to 'Unsubscribe', subscription_path(@question),
            method: :delete, remote: true, data: { type: :json },
            class: 'link-unsubscribe'
    - if policy(Answer).create?
      .row
        ul.nav.nav-pills
          li = link_to 'New answer', '#', class: 'link-new-answer'

app/views/questions/index.html.slim
- cache collection_cache_key_for :question do
  .questions
    - @questions.each do |question|
      div.row id="question-#{question.id}" data-id="#{question.id}" data-object="question"
        h5 = link_to question.title, question
        = question.body

= subscribe_to "/questions"

app/views/questions/new.html.slim
.row.new_question
  = form_for @question, html: { class: "form-horizontal" } do |f|
    .form-group
      = f.label :title, class: "col-sm-2 control-label"
      .col-sm-10
        = f.text_field :title, class: "form-control"
    .form-group
      = f.label :body, class: "col-sm-2 control-label"
      .col-sm-10
        = f.text_area :body, class: "form-control"
    .attachments_form
    .form-group
      .col-sm-offset-2.col-sm-10.add_attachment
        = link_to_add_association 'Add file', f, :attachments,
          partial: 'layouts/attachment_fields', class: "btn btn-default"
    .form-group
      .col-sm-offset-2.col-sm-10
        = f.submit "Save", class: "btn btn-default"

app/views/questions/show.html.slim
- cache @question do
  .row
    .col-xs-11.col-xs-offset-1.question id="question-#{@question.id}" data-id="#{@question.id}"
      .row
        .col-xs-7.question
          = render @question
        .col-xs-5.new-forms
          - if policy(Answer).create?
            - cache 'new_answer_form' do
              .new_answer
                = render partial: 'answers/form', locals: { answer: [@question, @question.answers.build] }
          - if policy(@question).update?
            .edit_question
              = render partial: 'form', locals: { question: @question }
      .row
        .col-xs-7.col-xs-offset-5
          .row.comments
            = render @question.comments
          .row
            - if policy(Comment).create?
              = link_to 'Add comment', '#', class: 'link-new-comment'
              = render partial: 'comments/form', locals: { commentable: @question, comment: @question.comments.build }
  .row
    hr
  .row
    .col-xs-10.col-xs-offset-2.answers data={question_id: "#{@question.id}"}
      = render @question.answers

= subscribe_to "/questions/#{@question.id}"
= subscribe_to "/questions/#{@question.id}/answers"
= subscribe_to "/questions/#{@question.id}/comments"

app/views/questions/update.js.erb
<% if @question.errors.present? %>
  <%= render "layouts/error", errors: @question.errors %>
<% else %>
  <% if remotipart_submitted? %>
    $('div.question .question').html("<%= j "#{render @question}" %>");
    $('div.edit_question').html("<%= j "#{render 'form', question: @question}" %>");
    $('div.question .comments').html("<%= j "#{render @question.comments}" %>");
  <% else %>
    $('div.question .question').html('<%= j render @question %>');
    $('div.edit_question').html('<%= j render "form", question: @question %>');
    $('div.question .comments').html('<%= j render @question.comments %>');
  <% end %>
  <% publish_to "/questions/#{@question.id}" do %>
    if (<%= @question.user_id %> != gon.user_id) {
      $('div.question .question').html("<%= j render @question %>");
    }
  <% end %>
  bindClickEditQuestion();
  bindAddFiles();
  bindClickClose();
  bindAddFiles();
  bindPlaceFiles();
<% end %>