config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :users, only: :show

  root 'questions#index'

  concern :votable do
    member do
      patch 'like'
      patch 'dislike'
      delete 'unvote'
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end

  get 'search' => 'search#search'
  post 'search' => 'search#search'

  resources :questions, concerns: [:votable, :commentable], shallow: true do
    resources :subscriptions, only: [:create, :destroy]
    resources :answers, concerns: [:votable, :commentable] do
      member do
        patch 'set_best'
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers
      end
    end
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  # respond_to :json

  def search
    authorize :search
    @result = Search.find(params[:query], params[:scope], params[:page])
    respond_with @result
  end
end

app/helpers/search_helper.rb
module SearchHelper
  def options_scope
    options = Search::SCOPES.map {|s| [t('.' + s), s]}
    options_for_select(options)
  end

  def select_search_scope
    select_tag :scope, options_scope, class: 'form-control'
  end

  def result_title(item)
    case item
    when Question
      link_to "Question \"#{item.title}\"", question_path(item.id)
    when Answer
      link_to "Answer for \"#{item.question.title}\"", question_path(item.question.id)
    when Comment
      if item.commentable_type == "Question"
        link_to "Comment for \"#{item.commentable.title}\"", question_path(item.commentable.id)
      else
        link_to "Comment for answer \"#{item.commentable.question.title}\"", question_path(item.commentable.question.id)
      end
    when User
      "User:"
    end    
  end

  def result_body(item)
    case item
    when User
      item.email
    else
      item.body
    end    
  end
end

app/views/search/search.html.slim
- provide :title
.content-block#search-block
  .row
    .col-middle
      = form_tag search_url do
        .form-group
          = label_tag :query, t('.query')
          = text_field_tag :query, '', class: 'form-control'
        .form-group
          = label_tag :scope, t('.scope')
          = select_search_scope
        = submit_tag "Find...", class: "btn btn-primary"
  - unless @result.nil?
    - if @result.empty?
      .row
        .col-middle
          p Unfortunately, the search returned no results.
    - else
      .row
        .col-full
          h2 Results:
      .results-subblock
        - @result.each do |item|
          .row.result-row
            .col-full
              .result-title
                = result_title(item)
              .result-body
                = result_body(item)
          .row
            .col-full
              hr
    .row
      .col-middle.text-center
        = will_paginate @result