config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :users, only: :show

  root 'questions#index'

  concern :votable do
    member do
      patch 'like'
      patch 'dislike'
      delete 'unvote'
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end

  get 'search' => 'search#search'
  post 'search' => 'search#search'

  resources :questions, concerns: [:votable, :commentable], shallow: true do
    resources :subscriptions, only: [:create, :destroy]
    resources :answers, concerns: [:votable, :commentable] do
      member do
        patch 'set_best'
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers
      end
    end
  end

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  include Votable
  include Attachable
  include Commentable

  belongs_to :user
  belongs_to :question

  validates :user_id, :question_id, :body, presence: true

  default_scope -> { order(best: :desc) }
  
  after_save :send_email_to_subscribers

  def set_best
    ActiveRecord::Base.transaction do
      self.question.answers.update_all(best: false)
      self.update!(best: true)
    end
  end

  private
    def send_email_to_subscribers
      QuestionSubscribersJob.perform_later(question, self)
    end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  include Voted

  before_action :authenticate_user!
  before_action :load_question, only: :create
  before_action :load_answer, except: :create
  after_action :publish_to

  respond_to :js, :json

  def create
    authorize Answer
    @answer = @question.answers.create(answer_params.merge({ user: current_user }))
    respond_with(@answer)
  end

  def update
    authorize @answer
    @answer.update(answer_params)
    respond_with(@answer)
  end

  def destroy
    authorize @answer
    respond_with(@answer.destroy)
  end

  def set_best
    authorize @answer
    respond_with(@answer.set_best)
  end

  private
    def load_question
      @question = Question.find(params[:question_id])
    end

    def load_answer
      @answer = Answer.find(params[:id])
    end

    def publish_to
      PrivatePub.publish_to("/questions/#{@answer.question_id}/answers",
            answer: @answer.to_json, attachments: @answer.attachments.to_json,
            question_owner_id: @answer.question.user_id.to_json,
            action: self.action_name, rating: @answer.rating
      ) if @answer.errors.empty?
    end

    def answer_params
      params.require(:answer).permit(:body, attachments_attributes: [:id, :file, :_destroy])
    end
end

app/controllers/api/v1/answers_controller.rb
class Api::V1::AnswersController < Api::V1::BaseController
  before_action :find_question
  before_action :find_answer, only: :show

  def index
    authorize :api
    @answers = @question.answers.all
    respond_with @answers
  end

  def show
    authorize :api
    respond_with @answer
  end

  def create
    authorize :api
    respond_with(@answer = @question.answers.create(answer_params.merge({ user: current_resource_owner })))
  end

  private
    def find_question
      @question = Question.find(params[:question_id])
    end
    
    def find_answer
      @answer = Answer.find(params[:id])
    end

    def answer_params
      params.require(:answer).permit(:body)
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_answer.html.slim
- cache answer do
  - if answer.persisted?
    .answer id = "answer-#{answer.id}"
      .row
        .col-xs-1.votes
          .row.text-center.best
            .status
              - if answer.best
                h5 Best
          = render 'layouts/vote_links', object: answer
        .col-xs-offset-1.col-xs-5
          = answer.body
          = render 'layouts/attachments', object: answer
          - if user_signed_in?
            - cache 'answer_links'
              ul.nav.nav-pills
                - if policy(answer).update?
                  li => link_to 'Edit', '#', id: answer.id, class: 'edit_answer'
                - if policy(answer).destroy?
                  li = link_to 'Delete', answer_path(answer), method: :delete,
                    class: "delete-answer-link", remote: true
                - if policy(answer).set_best?
                  li =< link_to 'Set best', set_best_answer_path(answer), method: :patch, remote: true, data: { type: :json }
        - cache 'answer_form'
          .col-xs-5
            = render 'answers/form', answer: answer
      .row
        .col-xs-7.col-xs-offset-5
          .row.comments
            = render answer.comments
          .row
            - if policy(Comment).create?
              = link_to 'Add comment', '#', class: 'link-new-comment'
              - cache 'comment_form'
                = render partial: 'comments/form', locals: { commentable: answer, comment: answer.comments.build }
      .row
        hr

= subscribe_to "/answers/#{answer.id}/comments"

app/views/answers/_form.html.slim
= form_for answer, remote: true, html: { class: "form-horizontal edit_answer" } do |f|
  .row
    .col-xs-1.col-xs-offset-11
      = link_to '#', class: "link-close" do
        span.glyphicon.glyphicon-remove
  .row
    .col-xs-12
      .form-group
        .col-xs-2
          = f.label :body, "Your answer", class: "control-label"
        .col-xs-10
          = f.text_area :body, class: "form-control"
      .attachments_form
        = f.fields_for :attachments do |attachment|
          = render 'layouts/attachment_fields', f: attachment, object: answer
      .form-group
        .col-sm-offset-2.col-sm-10.add_attachment
          = link_to_add_association 'Add file', f, :attachments,
              partial: 'layouts/attachment_fields', class: "btn btn-default"
      .form-group
        .col-sm-offset-2.col-sm-10
          = f.submit "Save", class: "btn btn-default"

app/views/answers/create.js.erb
<% if @answer.errors.present? %>
  <%= render "layouts/error", errors: @answer.errors %>
<% else %>
  $('.new_answer #answer_body').val('');
  $('.new_answer .form-control').val('');
  $('form.edit_answer').hide();
  <% if remotipart_submitted? %>
    $('.answers').prepend("<%= j "#{render @answer}" %>");
  <% else %>
    $('.answers').prepend('<%= j render @answer %>');
  <% end %>
  bindClickEditAnswer();
  bindClickClose();
  bindAddFiles();
  bindPlaceFiles();
  bindClickNewComment();
<% end %>

app/views/answers/destroy.js.erb
$('div#answer-<%= @answer.id %>').remove();

app/views/answers/update.js.erb
<% if @answer.errors.present? %>
  <%= render "layouts/error", errors: @answer.errors %>
<% else %>
  <% if remotipart_submitted? %>
    $('div#answer-<%= @answer.id %>').html("<%= j "#{render @answer}" %>");
  <% else %>
    $('div#answer-<%= @answer.id %>').html('<%= j render @answer %>');
  <% end %>
  $('form#edit_answer_<%= @answer.id %>').hide();
  bindClickEditAnswer();
  bindClickClose();
  bindAddFiles();
  bindPlaceFiles();
<% end %>