config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  authenticate :user, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  
  use_doorkeeper
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  match '/users/:id/finish_signup' => 'users#finish_signup', via: [:get, :patch], :as => :finish_signup
  resources :users, only: :show

  root 'questions#index'

  concern :votable do
    member do
      patch 'like'
      patch 'dislike'
      delete 'unvote'
    end
  end

  concern :commentable do
    resources :comments, only: [:create, :destroy]
  end

  get 'search' => 'search#search'
  post 'search' => 'search#search'

  resources :questions, concerns: [:votable, :commentable], shallow: true do
    resources :subscriptions, only: [:create, :destroy]
    resources :answers, concerns: [:votable, :commentable] do
      member do
        patch 'set_best'
      end
    end
  end

  namespace :api do
    namespace :v1 do
      resources :profiles, only: :index do
        get :me, on: :collection
      end

      resources :questions do
        resources :answers
      end
    end
  end

end

app/views/layouts/_attachment_fields.html.slim
.form-group.row.attachment
    .col-xs-offset-2.col-xs-8
      .input-group
        span.input-group-btn
          span.btn.btn-primary.btn-file
            | Browse...
            = f.file_field :file
        - if f.object.persisted?
          = f.text_field :file, class: "form-control", disabled: true,
            value: "#{f.object.file.identifier}"
        - else
          = f.text_field :file, class: "form-control", disabled: true
    - if f.object.persisted?
      .col-xs-2.checkbox.text-right
        = f.check_box :_destroy, id: "#{klass_name(object)}_#{object.id}_attachment_#{f.object.id}_destroy"
    - else
      .col-xs-2.input-group
        = link_to_remove_association "<span class='glyphicon glyphicon-remove'></span>".html_safe,
          f, { wrapper_class: 'attachment', class: 'btn btn-danger' }

app/views/layouts/_attachments.html.slim
- if object.attachments.any?
  h5 Attachments:
  ul
    - object.attachments.each do |a|
      li id="attachment-#{a.id}"
        => link_to a.file.identifier, a.file.url

app/views/layouts/_error.html.erb
<% errors.full_messages.each do |message| %>
    $('#errors').html('<div class="alert alert-danger"><%= j message %></div>')
                .show()
                .delay(1000)
                .fadeOut(function(){
                  $(this).empty();
                });
<% end %>

app/views/layouts/_vote_links.html.slim
- cache 'vote_links' do
  .row.rating.text-center
      h6 Rating:
      h3 = object.rating
  .row
    - if policy(object).can_vote?
      ul.nav.nav-pills.center-pills#vote-links
        li.dislike = vote_link(object, :dislike)
        li.like = vote_link(object, :like)
    - if policy(object).unvote?
      ul.nav.nav-pills.center-pills#vote-links
        li.unvote = vote_link(object, :unvote)

app/views/layouts/application.html.slim
doctype html
html
  head
    title Qstack
    = include_gon(:init => true)
    = stylesheet_link_tag 'application',
      media: 'all',
      'data-turbolinks-track' => true
    = javascript_include_tag 'application',
      'data-turbolinks-track' => true
    = csrf_meta_tags

  body
    .wrapper
      header.container
        .row
          .col-xs-10.col-xs-offset-1.page-header
            .col-xs-4
              ul.nav.nav-pills
                - if user_signed_in?
                  li = link_to 'Sign out', destroy_user_session_path, :method => :delete
                  li = link_to 'New question', new_question_path
                - else
                  li = link_to 'Sign in', new_user_session_path
                  li = link_to 'New user', new_user_registration_path
            .col-xs-2
              h4 = link_to 'QnA', root_path
            .col-xs-3.search
              ul.nav.nav-pills
                - if policy(:search).search?
                  li = link_to 'Search', search_path
            .col-xs-3
              - if user_signed_in?
                h5 Welcome, #{current_user.email}
        .row
          .col-xs-6.col-xs-offset-3#errors
            - if flash.present?
              = flash_messages
      .container
        = yield